"""
================================================================================
RED-TEAM CSV AUDIT SCRIPT: EXPLICIT BOUNDS VERIFICATION
================================================================================

This script performs a rigorous mathematical audit on the characteristic 
polynomial invariants (a1, a2) and the resulting Jacobian group orders 
generated by the C++ geometric sieve.

For a genus 2 hyperelliptic curve over GF(q), the characteristic polynomial 
of the Frobenius endomorphism is:
    P(T) = T^4 + a1*T^3 + a2*T^2 + q*a1*T + q^2

This script verifies that every curve generated adheres to the absolute 
topological constraints defined by the Hasse-Weil theorem and Honda-Tate theory.
It guarantees that no mathematically impossible coordinate pairs (such as those
caused by quadratic twist anomalies) enter the final database.
"""

import csv
import math
import glob
import os

def audit_csv_files():
    """
    Iterates through all 'gf*_exact_curves.csv' files in the current directory
    and applies five strict mathematical bounds tests to each row.
    """
    # Find all generated CSV files
    csv_files = glob.glob("gf*_exact_curves.csv")
    
    if not csv_files:
        print("No CSV files found. Make sure the C++ sieve has finished running.")
        return

    total_rows = 0
    anomalies = 0
    
    print("==========================================================")
    print(" RED-TEAM CSV AUDIT: EVALUATING TRACES AND HASSE-WEIL BOUNDS ")
    print("==========================================================")
    
    for file in sorted(csv_files):
        print(f"Auditing {file}...")
        file_anomalies = 0
        
        with open(file, 'r') as f:
            reader = csv.DictReader(f)
            
            # Verify the new headers exist
            required_headers = {'q', 'a1', 'a2', 'base_field_order', 'cm_trace_parity'}
            if not required_headers.issubset(set(reader.fieldnames)):
                print(f"  [ERROR] Missing headers in {file}. Found: {reader.fieldnames}")
                anomalies += 1
                continue

            for row_num, row in enumerate(reader, start=2): # start=2 accounts for 0-index and header row
                total_rows += 1
                try:
                    q = int(row['q'])
                    a1 = int(row['a1'])
                    a2 = int(row['a2'])
                    base_field_order = int(row['base_field_order'])
                    trace_parity = int(row['cm_trace_parity'])
                    
                    # ---------------------------------------------------------
                    # 1. Base Field Order Equation
                    # MATHEMATICAL EXPLANATION:
                    # The number of rational points on the Jacobian (the geometric 
                    # order N) is found by evaluating the characteristic polynomial 
                    # of the Frobenius endomorphism at T = 1.
                    # Equation: N = P(1) = 1 + a1 + a2 + q*a1 + q^2
                    # ---------------------------------------------------------
                    expected_order = 1 + a1 + a2 + q * a1 + q * q
                    if base_field_order != expected_order:
                        print(f"  [Row {row_num}] Mismatch: Computed Order {expected_order} != CSV Order {base_field_order}")
                        file_anomalies += 1
                        
                    # ---------------------------------------------------------
                    # 2. Honda-Tate a1 Bound
                    # MATHEMATICAL EXPLANATION:
                    # By the Weil conjectures, the roots of P(T) have an absolute 
                    # value of sqrt(q). Because a1 represents the negative sum 
                    # of the real-valued root pairings (x1 + x2), the maximum 
                    # theoretical limit is absolutely bounded.
                    # Bound: |a1| <= 4 * sqrt(q)
                    # ---------------------------------------------------------
                    a1_limit = 4 * math.sqrt(q)
                    if abs(a1) > a1_limit + 1e-9: # 1e-9 buffer for float precision
                        print(f"  [Row {row_num}] a1 Bound Violation: {a1} exceeds {a1_limit}")
                        file_anomalies += 1
                        
                    # ---------------------------------------------------------
                    # 3. Honda-Tate a2 Bounds
                    # MATHEMATICAL EXPLANATION:
                    # The real-valued roots x1 and x2 must satisfy a discriminant
                    # condition: Delta = a1^2 - 4(a2 - 2q) >= 0. 
                    # Solving for a2 generates the upper bound.
                    # Furthermore, x1 and x2 must lie within [-2*sqrt(q), 2*sqrt(q)],
                    # which mathematically enforces the lower bound.
                    # Upper Bound: a2 <= (a1^2 / 4) + 2q
                    # Lower Bound: a2 >= 2*sqrt(q)*|a1| - 2q
                    # ---------------------------------------------------------
                    upper_a2 = (a1 * a1) / 4.0 + 2 * q
                    lower_a2 = 2 * abs(a1) * math.sqrt(q) - 2 * q
                    if a2 > upper_a2 + 1e-9 or a2 < lower_a2 - 1e-9:
                        print(f"  [Row {row_num}] a2 Bound Violation: {a2} not in [{lower_a2}, {upper_a2}]")
                        file_anomalies += 1
                        
                    # ---------------------------------------------------------
                    # 4. Hasse-Weil Bounds for Genus 2 Jacobian
                    # MATHEMATICAL EXPLANATION:
                    # By maximizing and minimizing the algebraic integer roots of P(T), 
                    # the total volume of the Jacobian is absolutely bounded by the 
                    # Hasse-Weil limits. No valid curve can exist outside this window.
                    # N_min = (q + 1 - 2*sqrt(q))^2
                    # N_max = (q + 1 + 2*sqrt(q))^2
                    # ---------------------------------------------------------
                    n_min = (q + 1 - 2 * math.sqrt(q)) ** 2
                    n_max = (q + 1 + 2 * math.sqrt(q)) ** 2
                    if base_field_order < n_min - 1e-9 or base_field_order > n_max + 1e-9:
                        print(f"  [Row {row_num}] Hasse-Weil Violation: {base_field_order} not in [{n_min}, {n_max}]")
                        file_anomalies += 1
                        
                    # ---------------------------------------------------------
                    # 5. Parity Check
                    # MATHEMATICAL EXPLANATION:
                    # The parity of the Cartier-Manin trace extracted during 
                    # point-counting must exactly match the modulo 2 reduction 
                    # of the a1 invariant (Trace of Frobenius).
                    # ---------------------------------------------------------
                    expected_parity = (a1 % 2 + 2) % 2
                    if trace_parity != expected_parity:
                        print(f"  [Row {row_num}] Parity Mismatch: a1={a1}, parity={trace_parity}")
                        file_anomalies += 1

                except ValueError as e:
                    print(f"  [Row {row_num}] PARSING ERROR (Corrupt data): {e}")
                    file_anomalies += 1
                    
        anomalies += file_anomalies
        if file_anomalies == 0:
            print(f"  -> Pass: 0 anomalies found.")

    print("==========================================================")
    print("                      FINAL RESULTS                       ")
    print("==========================================================")
    print(f"Total CSV Files Audited    : {len(csv_files)}")
    print(f"Total Curve Rows Validated : {total_rows}")
    print(f"Total Trace Violations     : {anomalies}")
    
    if anomalies == 0:
        print("\nSTATUS: FLAWLESS.")
        print("The C++ geometric sieve output is mathematically pristine.")
        print("No quadratic twist anomalies detected.")

if __name__ == "__main__":
    audit_csv_files()
